# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - name: Pulling libatomsquip/quip from Docker Hub
      uses: docker://libatomsquip/quip
    # Run docker image
    - name: Run QUIP in image
      run: |
          using InteractiveUtils; versioninfo()
          using Pkg; Pkg.activate("."); Pkg.test("QUIP")
      shell: docker-compose run libatomsquip/quip /bin/real/bash -c "julia --color=yes --project {0}"
