# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Pull and run docker image
    - uses: docker://libatomsquip/quip
      with:
          entrypoint: /bin/real/bash
          #args: -it /bin/real/bash
    # Run in docker image
    - name: Install dependencies to libatomsquip container
      run: |
        python3 -m pip install --upgrade pip --user
        python3 -m pip install -U setuptools --user
        python3 -m pip install -U ase --user
        python3 -m pip install -U matscipy --user
        python3 -m pip install -U julia --user
    - name: Run QUIP within container
      run: |
          using InteractiveUtils; versioninfo()
          using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.activate("."); Pkg.test("QUIP")
      #shell: docker exec -it libatomsquip/quip /bin/real/bash -c "julia --color=yes --project {0}"
      shell: julia --color=yes --project {0}
      #shell: /bin/real/bash -c "julia --color=yes --project {0}"

